// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqsgypdzwogixwthszvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxc2d5cGR6d29naXh3dGhzenZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0NDgwNDQsImV4cCI6MjA3ODAyNDA0NH0.N74gPsJGxHPAUbqfJmOl9YPYh2npRezFwLrgmf6K9iE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});